# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
java_version=17

# Project
mod_id=packwiz_compatibility_check
mod_name=Packwiz Compatibility Check
mod_author=possible_triangle
mod_version=0.0.0-dev
mod_description=replaces the forge server compatiblity check with one for packwiz modpacks
release_type=alpha
maven_group=com.possible-triangle

# Common
mc_version=1.20.1

# Forge
forge_version=47.3.0

# Fabric
fabric_api_version=0.92.6+1.20.1
fabric_loader_version=0.17.3

# Publishing
repository=pssbletrngle/packwizcompatibilitycheck
modrinth_project_id=b8JkNsnd