# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.57</version>
#    <timestamp>2026-05-12T05:58:48.617Z</timestamp>
#    <hash>dbb00d8a44e9f658</hash>
# </meta>

name: Release
on:
  release:
    types: [published]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.event_name != 'push' }}

      - name: Build and upload
        run: ./gradlew build upload
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CHANGELOG: ${{ github.event.release.body }}
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
